/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appCalculaCostos.productoFinal.vista.controladorVista.vistaSwing;

import appCalculaCostos.costosMateriaPrima.modelo.logicaNegocio.CostoMateriaPrima;
import appCalculaCostos.costosMateriaPrima.modelo.logicaNegocio.Insumo;
import appCalculaCostos.costosMateriaPrima.vista.interfacesLogicas.IVistaCostosMp;
import appCalculaCostos.productoFinal.modelo.logicaNegocio.ProductoFinal;
import appCalculaCostos.productoFinal.vista.interfacesLogicas.IVistaProductos;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose
 */
public class VistaProductoFinalSwing extends javax.swing.JFrame implements IVistaProductos, IVistaCostosMp
{

    private Runnable guardarCallback;
    private Runnable mostrarProductosCallback;
    private Runnable mostrarInsumosCallback;
    private Runnable agregarIngredientesCallback;

    /**
     * Creates new form C
     */
    public VistaProductoFinalSwing()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel8 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlProducto = new javax.swing.JPanel();
        jtfNombre = new javax.swing.JTextField();
        jtfPorcentajeGanancia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlCostoMP = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlInferior = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pnlCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbInsumos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnlIngredientes = new javax.swing.JPanel();
        pnlCostoMO = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setEnabled(false);

        jtfNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfPorcentajeGanancia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Porcentaje de ganancia");

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jtfNombre)
                        .addComponent(jtfPorcentajeGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton1)))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jtfPorcentajeGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Producto", pnlProducto);

        pnlCostoMP.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel3.setText("Insumos");

        jLabel4.setText("Ingredientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(164, 164, 164))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15))
        );

        pnlCostoMP.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnlInferior.setBackground(new java.awt.Color(204, 255, 204));

        jButton2.setText("Finalizar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar ingrediente");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
        pnlInferior.setLayout(pnlInferiorLayout);
        pnlInferiorLayout.setHorizontalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInferiorLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        pnlInferiorLayout.setVerticalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        pnlCostoMP.add(pnlInferior, java.awt.BorderLayout.SOUTH);

        pnlCentral.setLayout(new java.awt.GridLayout());

        jtbInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"1", "Queso", "MATERIA_PRIMA", "g"},
                {"2", "Pure", "RECETA", "ml"},
                {"3", "Jamon", "MATERIA_PRIMA", "g"},
                {"4", "Piña", "MATERIA_PRIMA", "g"},
                {"5", "Masa", "RECETA", "Kg"}
            },
            new String []
            {
                "Id", "Nombre", "Tipo", "Unidad Medida"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbInsumos);

        pnlCentral.add(jScrollPane1);

        pnlIngredientes.setLayout(new javax.swing.BoxLayout(pnlIngredientes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane3.setViewportView(pnlIngredientes);

        pnlCentral.add(jScrollPane3);

        pnlCostoMP.add(pnlCentral, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Costo Materia Prima", pnlCostoMP);

        javax.swing.GroupLayout pnlCostoMOLayout = new javax.swing.GroupLayout(pnlCostoMO);
        pnlCostoMO.setLayout(pnlCostoMOLayout);
        pnlCostoMOLayout.setHorizontalGroup(
            pnlCostoMOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        pnlCostoMOLayout.setVerticalGroup(
            pnlCostoMOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Costo Mano Obra", pnlCostoMO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int index = 0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        index += 1;
        jTabbedPane1.setSelectedIndex(index);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed


    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VistaProductoFinalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VistaProductoFinalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VistaProductoFinalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VistaProductoFinalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VistaProductoFinalSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtbInsumos;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPorcentajeGanancia;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlCostoMO;
    private javax.swing.JPanel pnlCostoMP;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlIngredientes;
    private javax.swing.JPanel pnlProducto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarProductos(List<ProductoFinal> productos)
    {
        for (ProductoFinal p : productos)
        {

        }
    }

    @Override
    public Optional<ProductoFinal> getProductoSeleccionado()
    {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(this, mensaje, "Info", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public int getIDProductoSeleccionado()
    {
        var filaSeleccionada = jtbInsumos.getSelectedRow();
        int COLUMNA_ID = 0;
        if (filaSeleccionada != -1)
        {
            return Integer.parseInt((String) jtbInsumos.getValueAt(filaSeleccionada, COLUMNA_ID));
        }
        return -1;
    }

    @Override
    public String leerNombre()
    {
        return jtfNombre.getText();
    }

    @Override
    public double leerPorcentajeDeGanancia()
    {
        return Double.parseDouble(jtfPorcentajeGanancia.getText());
    }

    @Override
    public void iniciarVista()
    {
        this.setVisible(true);
        actualizarVista();

    }

    @Override
    public void mostrarMensajeError(String mensajeError)
    {
        JOptionPane.showMessageDialog(this, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void mostrarMensajeExito(String mensajeExito)
    {
        JOptionPane.showMessageDialog(this, mensajeExito, "Exito", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void setGuardarListener(Runnable callback)
    {
        this.guardarCallback = callback;
    }

    @Override
    public void setEliminarListener(Runnable callback)
    {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setActualizarListener(Runnable callback)
    {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setMostrarProductosListener(Runnable callback)
    {
        this.mostrarProductosCallback = callback;
    }

    @Override
    public void actualizarVista()
    {
        if (mostrarProductosCallback != null)
        {
            mostrarProductosCallback.run();
        }
    }

    @Override
    public void setMostrarInsumosListener(Runnable callback)
    {
        this.mostrarInsumosCallback = callback;
    }

    @Override
    public void setAgregarIngredientesListener(Runnable callback)
    {
        this.agregarIngredientesCallback = callback;
    }

    @Override
    public void mostrarInsumos(List<Insumo> insumos)
    {
        DefaultTableModel modelo = (DefaultTableModel) jtbInsumos.getModel();
        modelo.setRowCount(0); // Limpia la tabla

        for (Insumo i : insumos)
        {
            modelo.addRow(new Object[]
            {
                i.getId(),
                i.getNombre(),
                i.getTipoInsumo(),
                i.getUnidadDeMedida().getSimbolo()
            });
        }
    }

    @Override
    public void mostrarIngredientes(CostoMateriaPrima materiaPrima)
    {
        var ingredientes = materiaPrima.getInsumosUsados(); // HashMap<Insumo, Double>
        pnlIngredientes.removeAll(); // Limpia el panel antes de cargar nuevos ingredientes

        for (var entry : ingredientes.entrySet())
        {
            Insumo i = entry.getKey();
            double cantidad = entry.getValue();

            panelCantidadInsumo p1 = new panelCantidadInsumo();
            p1.setNombreInsumo(i.getNombre());
            p1.setCantidad(String.valueOf(cantidad));
            p1.setCosto(String.valueOf(i.getCostoPorUnidad() * cantidad));

            pnlIngredientes.add(p1);
        }

        pnlIngredientes.revalidate();
        pnlIngredientes.repaint();
    }

}
